"""empty message

Revision ID: 70a33f7c9286
Revises: b177fbe76264
Create Date: 2023-03-10 11:31:36.802232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a33f7c9286'
down_revision = 'b177fbe76264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=320), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
